"""Configuration parameters for the video surveillance pipeline."""

GAUSSIAN_BLUR_KERNEL = (5, 5)
GAUSSIAN_BLUR_SIGMA  = 0
CLAHE_CLIP_LIMIT     = 2.0
CLAHE_TILE_GRID      = (8, 8)

CANNY_THRESHOLD_LOW  = 50
CANNY_THRESHOLD_HIGH = 150

HOG_ORIENTATIONS     = 9
HOG_PIXELS_PER_CELL  = (8, 8)
HOG_CELLS_PER_BLOCK  = (2, 2)

MOG2_HISTORY         = 500
MOG2_VAR_THRESHOLD   = 16
MOG2_DETECT_SHADOWS  = False
MORPH_KERNEL_SIZE    = (5, 5)

MIN_CONTOUR_AREA     = 800
BBOX_COLOR           = (0, 255, 0)
BBOX_THICKNESS       = 2

MAX_DISAPPEARED      = 30
MAX_DISTANCE         = 100

OUTPUT_DIR           = "outputs"
OUTPUT_FPS           = 25
FOURCC               = "mp4v"
OVERLAY_FONT_SCALE   = 0.55
OVERLAY_FONT_COLOR   = (0, 255, 255)
OVERLAY_FONT_THICKNESS = 1
